services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: starthub-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - starthub_network


  starthub-api:
    image: smilekundev/starthub-api
    restart: always
    container_name: starthub-api
    depends_on:
      - db
    volumes:
      - static_volume:/app/starthub/staticfiles
    env_file:
      - .env
    networks:
      - starthub_network
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/share/nginx/html/static:ro
    depends_on:
      - starthub-api
    networks:
      - starthub_network
volumes:
  static_volume:
  postgresql-data:

networks:
  starthub_network:
    name: starthub_network
    driver: bridge