services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: starthub-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - starthub_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"

  starthub-api:
    image: smilekundev/starthub-api
    restart: always
    container_name: starthub-api
    depends_on:
      - db
    volumes:
      - static_volume:/app/starthub/staticfiles
    env_file:
      - .env
    networks:
      - starthub_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
volumes:
  static_volume:
  postgresql-data:

networks:
  starthub_network:
    name: starthub_network
    driver: bridge