# Generated by Django 5.2.1 on 2025-06-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="description",
        ),
        migrations.AlterField(
            model_name="companyfounder",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="founder", to="domain.company"
            ),
        ),
    ]
