# Generated by Django 5.2.1 on 2025-06-04 09:40

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="first-name-temp",
                max_length=50,
                validators=[django.core.validators.RegexValidator(re.compile("^[\\w_-]+$"))],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="last-name-temp",
                max_length=50,
                validators=[django.core.validators.RegexValidator(re.compile("^[\\w_-]+$"))],
            ),
            preserve_default=False,
        ),
    ]
