# Generated by Django 5.2.1 on 2025-05-26 09:15

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0002_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="FundingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="name", unique=True)),
            ],
            options={
                "verbose_name": "Funding Model",
                "verbose_name_plural": "Funding Models",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from="name", unique=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from="name", unique=True),
                ),
                ("description", models.TextField()),
                ("business_id", models.CharField(max_length=32, unique=True)),
                ("business_plan", models.FileField(blank=True, null=True, upload_to="business_plans/")),
                ("established_date", models.DateField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="domain.country")),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="team_members", to="domain.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from="name", unique=True),
                ),
                ("description", models.TextField()),
                ("goal_sum", models.DecimalField(decimal_places=2, max_digits=12)),
                ("current_sum", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("deadline", models.DateField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funding_model",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="domain.fundingmodel"),
                ),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="domain.projectcategory"),
                ),
                ("team", models.ManyToManyField(to="domain.teammember")),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="CompanyAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="domain.company"
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "key")},
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
