# Generated by Django 5.2.1 on 2025-06-05 13:01

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0002_remove_user_username_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(re.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).+$")),
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(64),
                ],
            ),
        ),
    ]
