# Generated by Django 5.2.1 on 2025-06-14 13:18

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_userfavorite"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userfavorite",
            table="user_favorites",
        ),
        migrations.CreateModel(
            name="ProjectPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_photo",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
