# Generated by Django 5.2.1 on 2025-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_user_picture_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="stage",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
