# Generated by Django 5.2.1 on 2025-06-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0004_alter_userfavorite_table_projectphoto"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectPhoto",
            new_name="ProjectImage",
        ),
        migrations.AlterModelTable(
            name="projectimage",
            table="project_images",
        ),
    ]
