# Generated by Django 5.2.1 on 2025-06-15 11:50

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0004_alter_userfavorite_table_projectphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="default first name",
                max_length=50,
                validators=[django.core.validators.RegexValidator(re.compile("^[\\w_-]+$"))],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="default last name",
                max_length=50,
                validators=[django.core.validators.RegexValidator(re.compile("^[\\w_-]+$"))],
            ),
        ),
    ]
