# Generated by Django 5.2.1 on 2025-06-10 12:18

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0004_project_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyFounder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "company_founder",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.AddField(
            model_name="company",
            name="founder",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company",
                to="domain.companyfounder",
            ),
        ),
    ]
