# Generated by Django 5.2.1 on 2025-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0005_rename_projectphoto_projectimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="order",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
