# Generated by Django 5.2.1 on 2025-06-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0005_companyfounder_company_founder"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
