# Generated by Django 5.2.1 on 2025-06-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0005_alter_user_first_name_alter_user_last_name"),
        ("domain", "0006_projectimage_order"),
    ]

    operations = []
