# Generated by Django 5.2.1 on 2025-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0006_project_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="established_date",
            field=models.DateField(),
        ),
    ]
