# Generated by Django 5.2.1 on 2025-06-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0007_alter_company_established_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="founder",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="company", to="domain.companyfounder"
            ),
        ),
    ]
