# Generated by Django 5.2.1 on 2025-06-18 08:59

import domain.models.role
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0007_merge_20250615_2050"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "permissions",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "roles",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(default=domain.models.role.get_default_role, to="domain.role"),
        ),
    ]
