# Generated by Django 5.2.1 on 2025-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0008_permission_role_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(to="domain.permission"),
        ),
    ]
