# Generated by Django 5.2.1 on 2025-06-19 10:56

import django.db.models.deletion
import domain.models.news
import domain.models.role
import domain.ports.model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0009_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(related_name="roles", to="domain.permission"),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                default=domain.models.role.get_default_role, related_name="users", to="domain.role"
            ),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField(default=domain.models.news.get_default_datetime_now)),
                ("updated_at", models.DateTimeField(default=domain.models.news.get_default_datetime_now)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
