# Generated by Django 5.2.1 on 2025-06-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0010_alter_role_permissions_alter_user_roles_news"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="news",
            table="news",
        ),
    ]
