# Generated by Django 5.2.1 on 2025-06-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0011_alter_news_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="domain.project"
            ),
        ),
    ]
