# Generated by Django 5.2.1 on 2025-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0012_alter_projectimage_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
