# Generated by Django 5.2.1 on 2025-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0012_alter_projectimage_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "ACTIVE"),
                    ("completed", "COMPLETED"),
                    ("draft", "DRAFT"),
                    ("under_moderation", "UNDER_MODERATION"),
                    ("fundraising", "FUNDRAISING"),
                    ("suspended", "SUSPENDED"),
                    ("cancelled", "CANCELLED"),
                ],
                default="active",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.CharField(
                choices=[
                    ("idea", "IDEA"),
                    ("mvp", "MVP"),
                    ("scale", "SCALE"),
                    ("validation", "VALIDATION"),
                    ("prototype", "PROTOTYPE"),
                ],
                max_length=16,
            ),
        ),
    ]
