# Generated by Django 5.2.1 on 2025-06-29 09:31

import django.db.models.deletion
import domain.ports.model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0013_user_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPhone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="phones", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_phones",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
