# Generated by Django 5.2.1 on 2025-06-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0013_project_status_alter_project_stage"),
        ("domain", "0014_userphone"),
    ]

    operations = []
