# Generated by Django 5.2.1 on 2025-07-02 12:27

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0015_merge_20250629_1856"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.CharField(max_length=255)),
                ("news", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="domain.news")),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
