# Generated by Django 5.2.1 on 2025-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0016_remove_news_image_newsimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="cover",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
