# Generated by Django 5.2.1 on 2025-07-18 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0017_news_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsimage",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="domain.news"
            ),
        ),
    ]
