# Generated by Django 5.2.1 on 2025-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0018_alter_newsimage_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(related_name="projects", to="domain.projectcategory"),
        ),
    ]
