# Generated by Django 5.2.1 on 2025-07-30 15:40

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0020_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="regions", to="domain.country"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "country")},
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="cities", to="domain.region"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "region")},
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("house_number", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("raw_address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="addresses", to="domain.country"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="addresses", to="domain.city"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="addresses", to="domain.region"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
