# Generated by Django 5.2.1 on 2025-07-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0021_region_city_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="domain.address"),
        ),
    ]
