# Generated by Django 5.2.1 on 2025-08-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0022_company_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="county",
            new_name="country",
        ),
    ]
