# Generated by Django 5.2.1 on 2025-08-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0023_rename_county_address_country"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table="addresses",
        ),
        migrations.AlterModelTable(
            name="city",
            table="cities",
        ),
        migrations.AlterModelTable(
            name="region",
            table="regions",
        ),
    ]
