# Generated by Django 5.2.1 on 2025-08-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0024_alter_address_table_alter_city_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="companies",
        ),
    ]
