# Generated by Django 5.2.1 on 2025-08-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0025_alter_company_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
