# Generated by Django 5.2.1 on 2025-08-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0026_company_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("country", "region", "city", "district", "street", "house_number", "postal_code")},
        ),
    ]
