# Generated by Django 5.2.1 on 2025-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0027_alter_address_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="goal_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={
                ("country", "region", "city", "district", "street", "house_number", "postal_code", "raw_address")
            },
        ),
    ]
