# Generated by Django 5.2.1 on 2025-08-06 13:04

import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0028_project_goal_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="domain.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
