# Generated by Django 5.2.1 on 2025-08-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0029_projectstep"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="projectstep",
            table="project_steps",
        ),
    ]
