# Generated by Django 5.2.1 on 2025-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0030_alter_projectstep_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="patent_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
