# Generated by Django 5.2.1 on 2025-08-07 15:22

import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0031_company_patent_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIncubator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="domain.project")),
            ],
            options={
                "db_table": "project_incubator",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
