# Generated by Django 5.2.1 on 2025-08-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0032_projectincubator"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="projectincubator",
            table="project_incubators",
        ),
    ]
