# Generated by Django 5.2.1 on 2025-08-08 06:19

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0033_alter_projectincubator_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectincubator",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="incubator", to="domain.project"
            ),
        ),
        migrations.CreateModel(
            name="ProjectAccelerator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="accelerator", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_accelerators",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
