# Generated by Django 5.2.1 on 2025-08-09 13:29

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0034_alter_projectincubator_project_projectaccelerator"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCrowdFunding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from="name", unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="crowdfunding", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_crowdfundings",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
