# Generated by Django 5.2.1 on 2025-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0035_projectcrowdfunding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcrowdfunding",
            name="amount",
            field=models.FloatField(),
        ),
    ]
