# Generated by Django 5.2.1 on 2025-08-11 07:24

import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0036_alter_projectcrowdfunding_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInvestment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization_name", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="investments", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_investments",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.CreateModel(
            name="ProjectInvestmentSocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="domain.projectinvestment",
                    ),
                ),
            ],
            options={
                "db_table": "project_investment_social_links",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
