# Generated by Django 5.2.1 on 2025-08-11 10:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0037_projectinvestment_projectinvestmentsociallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinvestment",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="default-organization-name",
                editable=False,
                max_length=255,
                populate_from="organization_name",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
