# Generated by Django 5.2.1 on 2025-08-11 22:09

import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0038_projectinvestment_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInvestmentPhone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="domain.projectinvestment",
                    ),
                ),
            ],
            options={
                "db_table": "project_investment_phones",
                "unique_together": {("project", "number")},
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
