# Generated by Django 5.2.1 on 2025-08-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0039_projectinvestmentphone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectinvestmentphone",
            old_name="project",
            new_name="investment",
        ),
        migrations.AlterUniqueTogether(
            name="projectinvestmentphone",
            unique_together={("investment", "number")},
        ),
    ]
