# Generated by Django 5.2.1 on 2025-08-12 13:14

import autoslug.fields
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0040_rename_project_projectinvestmentphone_investment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGovernmentGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "name_slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from="name", unique=True),
                ),
                ("amount", models.FloatField()),
                ("organization_name", models.CharField(max_length=255)),
                (
                    "organization_name_slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from="name", unique=True),
                ),
            ],
            options={
                "db_table": "project_government_grants",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
