# Generated by Django 5.2.1 on 2025-08-12 13:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0041_projectgovernmentgrant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectgovernmentgrant",
            old_name="name",
            new_name="grant_name",
        ),
        migrations.RemoveField(
            model_name="projectgovernmentgrant",
            name="name_slug",
        ),
        migrations.AddField(
            model_name="projectgovernmentgrant",
            name="grant_name_slug",
            field=autoslug.fields.AutoSlugField(
                default="grant_name_slug", editable=False, max_length=255, populate_from="grant_name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectgovernmentgrant",
            name="organization_name_slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=255, populate_from="organization_name", unique=True
            ),
        ),
    ]
