# Generated by Django 5.2.1 on 2025-08-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0042_rename_name_projectgovernmentgrant_grant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgovernmentgrant",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="government_grants",
                to="domain.project",
            ),
            preserve_default=False,
        ),
    ]
