# Generated by Django 5.2.1 on 2025-08-12 21:30

import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0043_projectgovernmentgrant_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBootstrap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bootstraps", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_bootstraps",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
