# Generated by Django 5.2.1 on 2025-08-13 19:21

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0044_projectbootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBankLoan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization_name", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("terms", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bank_loans", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "bank_loans",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
