# Generated by Django 5.2.1 on 2025-08-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0045_projectbankloan"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="aov",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="arppu",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="arpu",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="cac",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="churn_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="conversion_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="ltv",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="nps",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="roi",
            field=models.FloatField(null=True),
        ),
    ]
