# Generated by Django 5.2.1 on 2025-08-14 14:17

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0046_project_aov_project_arppu_project_arpu_project_cac_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_files",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
