# Generated by Django 5.2.1 on 2025-08-15 01:55

import django.db.models.deletion
from django.db import migrations, models

import domain.ports.model


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0047_projectfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=255)),
                ("order", models.SmallIntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_media",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
