# Generated by Django 5.2.1 on 2025-08-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0048_projectmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="sub_title",
            field=models.TextField(null=True),
        ),
    ]
