# Generated by Django 5.2.1 on 2025-08-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0049_news_sub_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="sub_title",
            new_name="subtitle",
        ),
    ]
