# Generated by Django 5.2.1 on 2025-08-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0050_rename_sub_title_news_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="name_kz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_kz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
