# Generated by Django 5.2.1 on 2025-08-18 18:17
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def rename_name_en_from_original_name_for_region_and_city(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Region = apps.get_model("domain", "Region")
    City = apps.get_model("domain", "City")

    for region in Region.objects.all():
        original_name = region.__dict__["name"]
        region.name_en = original_name
        region.save()

    for city in City.objects.all():
        original_name = city.__dict__["name"]
        city.name_en = original_name
        city.save()


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0051_city_name_en_city_name_kz_city_name_ru_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_name_en_from_original_name_for_region_and_city),
    ]
