# Generated by Django 5.2.1 on 2025-08-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0052_rename_name_en_from_original_name_for_region_and_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="name_kz",
            new_name="name_kk",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="name_kz",
            new_name="name_kk",
        ),
    ]
