# Generated by Django 5.2.1 on 2025-08-19 15:58

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0053_rename_name_kz_city_name_kk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectUsefulLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="useful_links", to="domain.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_useful_links",
                "unique_together": {("project", "url")},
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
