# Generated by Django 5.2.1 on 2025-08-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0054_projectusefullink"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "ACTIVE"),
                    ("completed", "COMPLETED"),
                    ("draft", "DRAFT"),
                    ("under_moderation", "UNDER_MODERATION"),
                    ("fundraising", "FUNDRAISING"),
                    ("suspended", "SUSPENDED"),
                    ("cancelled", "CANCELLED"),
                    ("rejected", "REJECTED"),
                    ("deactivated", "DEACTIVATED"),
                ],
                max_length=50,
            ),
        ),
    ]
