# Generated by Django 5.2.1 on 2025-08-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0056_notification"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
    ]
