# Generated by Django 5.2.1 on 2025-08-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0058_alter_notification_is_read_usermessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermessage",
            old_name="message",
            new_name="content",
        ),
    ]
