# Generated by Django 5.2.1 on 2025-08-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0059_rename_message_usermessage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
