# Generated by Django 5.2.1 on 2025-08-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0062_projectreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectreport",
            old_name="report",
            new_name="content",
        ),
    ]
