# Generated by Django 5.2.1 on 2025-08-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0063_rename_report_projectreport_content"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="projectreport",
            table="project_reports",
        ),
    ]
