# Generated by Django 5.2.1 on 2025-08-26 21:13

import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0064_alter_projectreport_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("news", models.ManyToManyField(related_name="tags", to="domain.news")),
            ],
            options={
                "db_table": "news_tags",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
    ]
