# Generated by Django 5.2.1 on 2025-08-26 22:06

import django.db.models.deletion
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0065_alter_news_published_at_alter_news_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newstag",
            name="news",
        ),
        migrations.CreateModel(
            name="NewsTagLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("news", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="domain.news")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="domain.newstag")),
            ],
            options={
                "unique_together": {("news", "tag")},
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(related_name="news", through="domain.NewsTagLink", to="domain.newstag"),
        ),
    ]
