# Generated by Django 5.2.1 on 2025-08-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0066_remove_newstag_news_newstaglink_news_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsTagLink",
            new_name="NewsTagsLink",
        ),
        migrations.AlterModelTable(
            name="newstagslink",
            table="news_tags_links",
        ),
    ]
