# Generated by Django 5.2.1 on 2025-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0067_rename_newstaglink_newstagslink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingmodel",
            name="description",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="fundingmodel",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
    ]
