# Generated by Django 5.2.1 on 2025-08-27 23:20

import autoslug.fields
import domain.ports.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0068_fundingmodel_description_fundingmodel_recommended"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, max_length=110, populate_from="name", unique=True),
                ),
                ("description", models.CharField(max_length=2000, null=True)),
            ],
            options={
                "db_table": "project_stages",
            },
            bases=(models.Model, domain.ports.model.AbstractModel),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, max_length=265, populate_from="name", unique=True),
        ),
    ]
