# Generated by Django 5.2.1 on 2025-08-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0069_projectstage_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="stage_temp",
            field=models.ForeignKey("ProjectStage", on_delete=models.CASCADE, null=True, blank=True),
        ),
    ]
