# Generated by Django 5.2.1 on 2025-08-27 23:25

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


# noinspection PyPep8Naming
def transfer_stage_data(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Project = apps.get_model("domain", "Project")
    ProjectStage = apps.get_model("domain", "ProjectStage")

    for project in Project.objects.all():
        if getattr(project, "stage"):
            stage, created = ProjectStage.objects.get_or_create(name=project.stage)
            project.stage_temp = stage
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0070_add_temp_stage_field"),
    ]

    operations = [
        migrations.RunPython(transfer_stage_data),
    ]
