# Generated by Django 5.2.1 on 2025-08-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0071_copy_data_from_stage_to_temp_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="stage",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="stage_temp",
            new_name="stage",
        ),
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.ForeignKey("ProjectStage", on_delete=models.CASCADE),
        ),
    ]
