# Generated by Django 5.2.1 on 2025-08-28 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0072_auto_20250828_0458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="projects", to="domain.projectstage"
            ),
        ),
    ]
