from enum import StrEnum


class FileExtensionEnum(StrEnum):
    # Image
    DWG = "dwg"
    XCF = "xcf"
    JPG = "jpg"
    JPX = "jpx"
    PNG = "png"
    APNG = "apng"
    GIF = "gif"
    WEBP = "webp"
    CR2 = "cr2"
    TIF = "tif"
    BMP = "bmp"
    JXR = "jxr"
    PSD = "psd"
    ICO = "ico"
    HEIC = "heic"
    AVIF = "avif"

    # Video
    THREE_GP = "3gp"
    MP4 = "mp4"
    M4V = "m4v"
    MKV = "mkv"
    WEBM = "webm"
    MOV = "mov"
    AVI = "avi"
    WMV = "wmv"
    MPG = "mpg"
    FLV = "flv"

    # Audio
    AAC = "aac"
    MID = "mid"
    MP3 = "mp3"
    M4A = "m4a"
    OGG = "ogg"
    FLAC = "flac"
    WAV = "wav"
    AMR = "amr"
    AIFF = "aiff"

    # Archive
    BR = "br"
    RPM = "rpm"
    DCM = "dcm"
    EPUB = "epub"
    ZIP = "zip"
    TAR = "tar"
    RAR = "rar"
    GZ = "gz"
    BZ2 = "bz2"
    SEVEN_Z = "7z"
    XZ = "xz"
    PDF = "pdf"
    EXE = "exe"
    SWF = "swf"
    RTF = "rtf"
    EOT = "eot"
    PS = "ps"
    SQLITE = "sqlite"
    NES = "nes"
    CRX = "crx"
    CAB = "cab"
    DEB = "deb"
    AR = "ar"
    Z = "Z"
    LZO = "lzo"
    LZ = "lz"
    LZ4 = "lz4"
    ZSTD = "zstd"

    # Document
    DOC = "doc"
    DOCX = "docx"
    ODT = "odt"
    XLS = "xls"
    XLSX = "xlsx"
    ODS = "ods"
    PPT = "ppt"
    PPTX = "pptx"
    ODP = "odp"

    # Font
    WOFF = "woff"
    WOFF2 = "woff2"
    TTF = "ttf"
    OTF = "otf"

    # Application
    WASM = "wasm"


class MimeTypeEnum(StrEnum):
    # Image
    IMAGE_DWG = "image/vnd.dwg"
    IMAGE_XCF = "image/x-xcf"
    IMAGE_JPEG = "image/jpeg"
    IMAGE_JPX = "image/jpx"
    IMAGE_PNG = "image/png"
    IMAGE_APNG = "image/apng"
    IMAGE_GIF = "image/gif"
    IMAGE_WEBP = "image/webp"
    IMAGE_CR2 = "image/x-canon-cr2"
    IMAGE_TIFF = "image/tiff"
    IMAGE_BMP = "image/bmp"
    IMAGE_JXR = "image/vnd.ms-photo"
    IMAGE_PSD = "image/vnd.adobe.photoshop"
    IMAGE_ICO = "image/x-icon"
    IMAGE_HEIC = "image/heic"
    IMAGE_AVIF = "image/avif"

    # Video
    VIDEO_3GPP = "video/3gpp"
    VIDEO_MP4 = "video/mp4"
    VIDEO_M4V = "video/x-m4v"
    VIDEO_MATROSKA = "video/x-matroska"
    VIDEO_WEBM = "video/webm"
    VIDEO_QUICKTIME = "video/quicktime"
    VIDEO_MSVIDEO = "video/x-msvideo"
    VIDEO_WMV = "video/x-ms-wmv"
    VIDEO_MPEG = "video/mpeg"
    VIDEO_FLV = "video/x-flv"

    # Audio
    AUDIO_AAC = "audio/aac"
    AUDIO_MIDI = "audio/midi"
    AUDIO_MPEG = "audio/mpeg"
    AUDIO_MP4 = "audio/mp4"
    AUDIO_OGG = "audio/ogg"
    AUDIO_FLAC = "audio/x-flac"
    AUDIO_WAV = "audio/x-wav"
    AUDIO_AMR = "audio/amr"
    AUDIO_AIFF = "audio/x-aiff"

    # Archive/Application
    APP_BROTLI = "application/x-brotli"
    APP_RPM = "application/x-rpm"
    APP_DICOM = "application/dicom"
    APP_EPUB = "application/epub+zip"
    APP_ZIP = "application/zip"
    APP_TAR = "application/x-tar"
    APP_RAR = "application/x-rar-compressed"
    APP_GZIP = "application/gzip"
    APP_BZIP2 = "application/x-bzip2"
    APP_7Z = "application/x-7z-compressed"
    APP_XZ = "application/x-xz"
    APP_PDF = "application/pdf"
    APP_MSDOWNLOAD = "application/x-msdownload"
    APP_SHOCKWAVE = "application/x-shockwave-flash"
    APP_RTF = "application/rtf"
    APP_OCTET_STREAM = "application/octet-stream"
    APP_POSTSCRIPT = "application/postscript"
    APP_SQLITE = "application/x-sqlite3"
    APP_NES = "application/x-nintendo-nes-rom"
    APP_CHROME_EXT = "application/x-google-chrome-extension"
    APP_CAB = "application/vnd.ms-cab-compressed"
    APP_DEB = "application/x-deb"
    APP_UNIX_ARCHIVE = "application/x-unix-archive"
    APP_COMPRESS = "application/x-compress"
    APP_LZOP = "application/x-lzop"
    APP_LZIP = "application/x-lzip"
    APP_LZ4 = "application/x-lz4"
    APP_ZSTD = "application/zstd"
    APP_MSWORD = "application/msword"
    APP_DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    APP_ODT = "application/vnd.oasis.opendocument.text"
    APP_EXCEL = "application/vnd.ms-excel"
    APP_XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    APP_ODS = "application/vnd.oasis.opendocument.spreadsheet"
    APP_POWERPOINT = "application/vnd.ms-powerpoint"
    APP_PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    APP_ODP = "application/vnd.oasis.opendocument.presentation"
    APP_FONT_WOFF = "application/font-woff"
    APP_FONT_SFNT = "application/font-sfnt"
    APP_WASM = "application/wasm"
