name: Deploy

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: starthub-vps
    steps:
      - name: Deploy project
        run: echo "Deploying..."