name: Deploy

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: starthub-vps
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: login to hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove old image (if exists)
        run: docker rmi starthub-api:old || true

      - name: Tag latest as old
        run: docker tag starthub-api:latest starthub-api:old || true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: smilekundev/starthub-api:latest