name: Main
on:
  push:
    branches:
      - master
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: Run mypy
        run: uv run mypy .
        working-directory: starthub

      - name: Run flake8
        run: uv run flake8 .
        working-directory: starthub

      - name: Run isort
        run: uv run isort . --check-only
        working-directory: starthub

      - name: Run black
        run: uv run black . --check
        working-directory: starthub